export const TOGGLE_ERROR_MODAL = 'TOGGLE_ERROR_MODAL';
export const GET_DATA_FROM_DB = 'GET_DATA_FROM_DB';
export const SWITCH_URL_SECTION = 'SWITCH_URL_SECTION';
export const SET_LOADING = 'SET_LOADING';
